modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
    modId="supertools"
    version="${file.jarVersion}"
    displayName="Super Tools"
    authors="Sidrus"
    description='''Some tools to make you SUPER!'''

[[dependencies.supertools]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.supertools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
